import { Subject } from "../models/subject.model.js";

const subjects = [
  "Research Methods",
  "Advanced Mathematics",
  "Data Analysis",
  "Technical Writing",
  "Project Management",
  "Internship / Practical Training",
  "Thesis / Capstone Project",
  "Algorithms",
  "Data Structures",
  "Operating Systems",
  "Database Systems",
  "Computer Networks",
  "Machine Learning",
  "Artificial Intelligence",
  "Distributed Systems",
  "Software Engineering",
  "Cloud Computing",
  "Cybersecurity",
  "Data Mining",
  "Big Data Analytics",
  "Statistics",
  "Deep Learning",
  "Data Visualization",
  "Big Data Systems",
  "Python for Data Science",
  "R Programming",
  "Natural Language Processing",
  "Predictive Analytics",
  "Embedded Systems",
  "Digital Signal Processing",
  "Computer Architecture",
  "VLSI Design",
  "Control Systems",
  "Wireless Communication",
  "Power Systems",
  "Analog Circuits",
  "Robotics",
  "Molecular Biology",
  "Genetics",
  "Biochemistry",
  "Bioinformatics",
  "Cell Biology",
  "Immunology",
  "Pharmacology",
  "Research Techniques",
  "Business Statistics",
  "Predictive Modeling",
  "Business Intelligence",
  "Marketing Analytics",
  "Financial Analytics",
  "Optimization Techniques",
  "Full-Stack Web Development",
  "Frontend Development (React, Next.js)",
  "Backend Development (Node.js, Spring Boot)",
  "DevOps Engineering",
  "CI/CD Pipelines",
  "Kubernetes",
  "Docker",
  "Microservices Architecture",
  "API Design & Development",
  "Systems Design",
  "Cloud Architecture (AWS, Azure, GCP)",
  "Serverless Computing",
  "Database Administration",
  "Data Engineering",
  "ETL Pipelines",
  "Data Warehousing",
  "MLOps",
  "Model Deployment",
  "Prompt Engineering",
  "AI Product Development",
  "Information Security",
  "Penetration Testing",
  "Risk Management",
  "Blockchain Fundamentals",
  "FinTech Systems",
  "Mobile App Development (iOS, Android)",
  "Human-Computer Interaction",
  "UI/UX Design",
  "Product Management",
  "Agile Methodologies",
  "Quantum Computing Basics",
  "Edge Computing",
  "IoT Systems",
  "AR/VR Development"
];

export const seedSubjects = async () => {
  try {
    for (const name of subjects) {
      await Subject.findOrCreate({
        where: { name },
      });
    }

    console.log("✅ Subjects seeded!");
  } catch (error) {
    console.error("❌ Error seeding subjects:", error);
  }
};
